# Generated by Django 3.2.7 on 2021-09-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_followingcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followingcomment',
            name='post',
        ),
    ]
