# Generated by Django 3.2.7 on 2021-09-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_followingcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='following_comment',
            field=models.IntegerField(null=True),
        ),
    ]
