# Generated by Django 3.2.7 on 2021-09-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210924_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='following_comment',
            new_name='following_comment_id',
        ),
    ]
