# Generated by Django 3.2.7 on 2021-09-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_following_comment_comment_following_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='following_comment_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
